### ISSUE TITLE
Authentication does not work anymore

### ISSUE THREAD

**Issue by Xavier74** [gysmo38/domoticz-python-melcloud#6]
Hello,

Since yesterday, authentication to melcloud does not work anymore.
On the melcloud website it is now required to agrea conditions on each signing request.
Plugin give back a 401 code.

Many thanks if you are able to fix this problem.

Best regards

**Comment by miczmc** [comment]
Hello,

same error in logs here with version: 0.7.6 of the plugin.

Regards,
Michel

**Comment by gysmo38** [comment]
Hello,
If you accept condition one time on the melcloud website, it should work. I juste tested now and it work for me.
Regards

**Comment by miczmc** [comment]
Hello,
Thank you for this feedback gysmo38. It fixed also for me. Please move this issue to solve.
Regards
Miczmc
